[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Lightweight Adobe Round 1B solution"
requires-python = ">=3.11"
dependencies = [
    "pdfplumber>=0.11.7",
    "numpy>=2.3.2",
    "PyPDF2>=3.0.1"  # Fallback for PDF extraction
]
